/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { a } from '@react-spring/three';

type GLTFResult = GLTF & {
  nodes: {
    ['node-0']: THREE.Mesh;
  };
  materials: {
    White: THREE.MeshStandardMaterial;
  };
};

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF('/three/PaperAirplane.glb') as
    | GLTFResult
    | any;

  return (
    <a.group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes['node-0'].geometry} material={materials.White} />
    </a.group>
  );
}

useGLTF.preload('/three/PaperAirplane.glb');
